// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyw8q62HiKYca7WhbdgUHWcPSm03IF_6c',
    appId: '1:762425861205:web:1d9b643c853dbea6f260dc',
    messagingSenderId: '762425861205',
    projectId: 'rankwise-9e100',
    authDomain: 'rankwise-9e100.firebaseapp.com',
    storageBucket: 'rankwise-9e100.firebasestorage.app',
    measurementId: 'G-6NBMN6T11H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrYtV2wBOg1n4A2nAcI5NhhgHdMVNq5w',
    appId: '1:762425861205:android:03a3d921c4a09e3bf260dc',
    messagingSenderId: '762425861205',
    projectId: 'rankwise-9e100',
    storageBucket: 'rankwise-9e100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUoK_9O_uC4aofYvxJnstIWyBdnH-gYA4',
    appId: '1:762425861205:ios:51d23b84bb1c0214f260dc',
    messagingSenderId: '762425861205',
    projectId: 'rankwise-9e100',
    storageBucket: 'rankwise-9e100.firebasestorage.app',
    iosBundleId: 'com.lakshyank.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUoK_9O_uC4aofYvxJnstIWyBdnH-gYA4',
    appId: '1:762425861205:ios:9c7b143b0c180834f260dc',
    messagingSenderId: '762425861205',
    projectId: 'rankwise-9e100',
    storageBucket: 'rankwise-9e100.firebasestorage.app',
    iosBundleId: 'com.example.upscQuestionsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyw8q62HiKYca7WhbdgUHWcPSm03IF_6c',
    appId: '1:762425861205:web:b2e4f977feb3051df260dc',
    messagingSenderId: '762425861205',
    projectId: 'rankwise-9e100',
    authDomain: 'rankwise-9e100.firebaseapp.com',
    storageBucket: 'rankwise-9e100.firebasestorage.app',
    measurementId: 'G-7C7LB1JBWX',
  );
}
